DELETE FROM `DateTimes`;
DELETE FROM `Directory`;
DELETE FROM `Extension`;
DELETE FROM `File`;
DELETE FROM `Types`;
DELETE FROM `Volume`;

DELETE FROM `MP3APIC`;
DELETE FROM `MP3Album`;
DELETE FROM `MP3Artist`;
DELETE FROM `MP3GEOB`;
DELETE FROM `MP3Header`;
DELETE FROM `MP3ID3`;
DELETE FROM `MP3POPM`;
DELETE FROM `MP3UFID`;
DELETE FROM `MP3URLS`;
DELETE FROM `MP3USLT`;
DELETE FROM `MP3Comments`;
